[package]
name = "rusty-vocabulary"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
gtk = "0.9.0"
relm = "0.20.0"
relm-derive = "0.20.0"
