[package]
name = "rusty-vocabulary"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = { version = "0.16", features = ["crossterm"], default-features = false}
anyhow = "1.0"
